Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Timeout: 5
    MemorySize: 128
    Architectures:
      - x86_64

Resources:
  BinaryApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      BinaryMediaTypes:
        - multipart/form-data
  DataEncryption:
    Type: AWS::KMS::Key
    Properties:
      EnableKeyRotation: true
  FileStoreS3:
    Type: AWS::S3::Bucket
  MetadataStore:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "code"
          AttributeType: "N"
        - AttributeName: "file"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "code"
          KeyType: "HASH"
        - AttributeName: "file"
          KeyType: "RANGE"
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: cmd/api/hello
      Handler: bootstrap
      Runtime: provided.al2023
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
  CreateFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      Policies:
        - S3WritePolicy:
            BucketName: !Ref FileStoreS3
        - DynamoDBCrudPolicy:
            TableName: !Ref MetadataStore
        - Statement:
            - Effect: Allow
              Action:
                - kms:GenerateDataKey
              Resource: !GetAtt DataEncryption.Arn
      CodeUri: cmd/api/create
      Handler: bootstrap
      Runtime: provided.al2023
      Events:
        CatchAll:
          Type: Api
          Properties:
            RestApiId: !Ref BinaryApiGateway
            Path: /create
            Method: POST
      Environment:
        Variables:
          FILESTORES3_BUCKET_NAME: !Ref FileStoreS3
          METADATA_STORE_NAME: !Ref MetadataStore
          DATA_ENCRYPTION_NAME: !Ref DataEncryption
  GetFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref MetadataStore
        - Statement:
            - Effect: Allow
              Action:
                - kms:Decrypt
              Resource: !GetAtt DataEncryption.Arn
      CodeUri: cmd/api/get
      Handler: bootstrap
      Runtime: provided.al2023
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /get/{id}
            Method: GET
      Environment:
        Variables:
          METADATA_STORE_NAME: !Ref MetadataStore
          DATA_ENCRYPTION_NAME: !Ref DataEncryption
