Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Timeout: 5
    MemorySize: 128
    Architectures:
      - x86_64

Resources:
  FileStoreS3:
    Type: AWS::S3::Bucket
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: cmd/api/hello
      Handler: bootstrap
      Runtime: provided.al2023
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
  CreateFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      Policies:
        - S3WritePolicy:
            BucketName: !Ref FileStoreS3
      CodeUri: cmd/api/create
      Handler: bootstrap
      Runtime: provided.al2023
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /create
            Method: POST
      Environment:
        Variables:
          FILESTORES3_BUCKET_NAME: !Ref FileStoreS3
  GetFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref MetadataStore
        - Statement:
            - Effect: Allow
              Action:
                - kms:Decrypt
              Resource: !GetAtt DataEncryption.Arn
      CodeUri: cmd/api/get
      Handler: bootstrap
      Runtime: provided.al2023
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /get/{id}
            Method: GET
  GetFileFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: cmd/api/getFile
      Handler: bootstrap
      Runtime: provided.al2023
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /getFile/{id}/{file}
            Method: GET
