Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Timeout: 5
    MemorySize: 128
    Architectures:
      - arm64

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: cmd/api/hello
      Handler: bootstrap
      Runtime: provided.al2023
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
